# Generated by Django 2.2 on 2019-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20190514_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
