# Generated by Django 2.2 on 2019-05-21 19:04

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20190521_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=120, unique=True, validators=[author.models.validate_email]),
        ),
    ]
